#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/laravel-worker/DispatchCommand.php';

// Check if console
if (PHP_SAPI === 'cli') {
    if ($argc >= 1) {
        unset($argv[0]);
        laravelWorker\dispatch_command(__DIR__, $argv);
    }
}
